<?php

namespace ContainerTxD2MoC;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator__F25NuNService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator..f25NuN' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator..f25NuN'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'customer' => ['privates', '.errored..service_locator..f25NuN.App\\Entity\\Customer', NULL, 'Cannot autowire service ".service_locator..f25NuN": it needs an instance of "App\\Entity\\Customer" but this type has been excluded in "config/services.yaml".'],
            'entityManager' => ['services', 'doctrine.orm.default_entity_manager', 'getDoctrine_Orm_DefaultEntityManagerService', false],
        ], [
            'customer' => 'App\\Entity\\Customer',
            'entityManager' => '?',
        ]);
    }
}
