<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerTxD2MoC\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerTxD2MoC/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerTxD2MoC.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerTxD2MoC\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerTxD2MoC\App_KernelDevDebugContainer([
    'container.build_hash' => 'TxD2MoC',
    'container.build_id' => '3c99ab9d',
    'container.build_time' => 1706034824,
    'container.runtime_mode' => \in_array(\PHP_SAPI, ['cli', 'phpdbg', 'embed'], true) ? 'web=0' : 'web=1',
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerTxD2MoC');
